---
- name: wait for ssh
  wait_for:
    host: "{{ libvirt_host_ssh_ip_address }}"
    port: >-
      {{ libvirt_result_winrm_port
          if (libvirt_result_winrm_port | int) > 0
        else
          libvirt_result_ssh_port
      }}
    timeout: 60 # seconds
  delegate_to: 127.0.0.1

- name: Wait a second
  wait_for:
    timeout: 1

- name: restart
  command: "virsh reboot {{ libvirt_result_domain_name }}"

- name: wait for ssh again
  wait_for:
    host: "{{ libvirt_host_ssh_ip_address }}"
    port: >-
      {{ libvirt_result_winrm_port
          if (libvirt_result_winrm_port | int) > 0
        else
          libvirt_result_ssh_port
      }}
    timeout: 60 # seconds
  delegate_to: 127.0.0.1
